# Generated by Django 6.1 on 2026-08-11 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_admin_fastmcp.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="McpClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        default=django_admin_fastmcp.models.make_prefix, max_length=48, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("redirect_uris", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="McpToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scopes", models.JSONField(default=list)),
                ("resource", models.CharField(blank=True, default="", max_length=500)),
                ("access_prefix", models.CharField(db_index=True, max_length=12, unique=True)),
                ("access_hash", models.CharField(max_length=64)),
                ("refresh_prefix", models.CharField(db_index=True, max_length=12, unique=True)),
                ("refresh_hash", models.CharField(max_length=64)),
                ("salt", models.CharField(max_length=32)),
                ("access_expires_at", models.DateTimeField()),
                ("refresh_expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="django_admin_fastmcp.mcpclient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [("write_via_mcp", "Can obtain the admin:write scope over MCP")],
            },
        ),
        migrations.CreateModel(
            name="McpAuthorizationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code_hash", models.CharField(max_length=64, unique=True)),
                ("scopes", models.JSONField(default=list)),
                ("redirect_uri", models.CharField(max_length=500)),
                ("code_challenge", models.CharField(max_length=128)),
                ("resource", models.CharField(blank=True, default="", max_length=500)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_admin_fastmcp.mcpclient",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_admin_fastmcp.mcptoken",
                    ),
                ),
            ],
        ),
    ]
